# Generated by Django 4.0.10 on 2024-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesApp', '0002_product_transaction_conversation_auxproduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='none', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
