# Generated by Django 4.0.10 on 2024-10-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesApp', '0003_remove_customuser_email_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxproduser',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
