# Generated by Django 4.0.10 on 2024-10-26 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagesApp', '0004_auxproduser_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
